# Generated by Django 5.2.17 on 2026-09-15 09:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Firma Adı')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bölge Adı')),
            ],
            options={
                'verbose_name': 'Bölge',
                'verbose_name_plural': 'Bölgeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ihale', 'İhale'), ('formen', 'Formen')], default='formen', max_length=20, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=80, verbose_name='Soyad')),
                ('status', models.CharField(choices=[('asil', 'Asıl'), ('yedek', 'Yedek')], default='asil', max_length=10, verbose_name='Durum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formen_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foremen', to='fleet.region', verbose_name='Sorumlu Bölge')),
            ],
            options={
                'verbose_name': 'Formen',
                'verbose_name_plural': 'Formenler',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Plaka')),
                ('vehicle_type', models.CharField(max_length=80, verbose_name='Araç Tipi')),
                ('status', models.CharField(choices=[('asil', 'Asıl'), ('yedek', 'Yedek')], default='asil', max_length=10, verbose_name='Durum')),
                ('backup_foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_vehicles', to='fleet.foreman', verbose_name='Yedek Formen')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.company', verbose_name='Firma')),
                ('primary_foreman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_vehicles', to='fleet.foreman', verbose_name='Asıl Formen')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.region', verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=80, verbose_name='Soyad')),
                ('duty', models.CharField(max_length=120, verbose_name='Görevi')),
                ('status', models.CharField(choices=[('asil', 'Asıl'), ('yedek', 'Yedek')], default='asil', max_length=10, verbose_name='Durum')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='fleet.company', verbose_name='Firma')),
                ('assigned_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='fleet.vehicle', verbose_name='Zimmetli Araç')),
            ],
            options={
                'verbose_name': 'Şoför',
                'verbose_name_plural': 'Şoförler',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_supervisor_name', models.CharField(blank=True, max_length=120, verbose_name='Görevlendirilen Birim Amiri')),
                ('assigned_supervisor_title', models.CharField(blank=True, max_length=120, verbose_name='Ünvanı')),
                ('dispatching_supervisor_name', models.CharField(blank=True, max_length=120, verbose_name='Aracı Sevk Eden Amir')),
                ('dispatching_supervisor_title', models.CharField(blank=True, default='Formen', max_length=120, verbose_name='Sevk Eden Ünvanı')),
                ('task_type', models.CharField(blank=True, max_length=150, verbose_name='Görevin Türü')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Gideceği Yer')),
                ('engine_hours_km', models.CharField(blank=True, max_length=100, verbose_name='Motor Saati / KM')),
                ('departure_datetime', models.DateTimeField(verbose_name='Çıkış Tarihi/Saati')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Varış Tarihi/Saati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='fleet.company', verbose_name='Firma')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='fleet.driver', verbose_name='Şoför')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='fleet.region', verbose_name='Bölge')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='fleet.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Görev Emri',
                'verbose_name_plural': 'Görev Emirleri',
                'ordering': ['-departure_datetime', '-id'],
            },
        ),
    ]
