# Generated by Django 5.2.17 on 2026-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Görev emri numarası için kısaltma (örn: DRN)', max_length=10, verbose_name='Kod'),
        ),
    ]
