# Generated by Django 5.2.17 on 2026-09-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletask',
            name='end_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Son KM'),
        ),
        migrations.AddField(
            model_name='vehicletask',
            name='start_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='İlk KM'),
        ),
    ]
